In [1]:
import numpy as np
from fmpy import *
import matplotlib.pyplot as plt
import random

In [2]:
fmu = 'ego_1.fmu'
dump(fmu)


Model Info

  FMI Version        2.0
  FMI Type           Co-Simulation
  Model Name         ego_1
  Description        None
  Platforms          linux64, win64
  Continuous States  0
  Event Indicators   0
  Variables          16
  Generation Tool    Simulink (R2024b)
  Generation Date    2025-01-29T10:36:16Z

Default Experiment

  Stop Time          5.0
  Step Size          0.1

Variables (input, output)

  Name               Causality              Start Value  Unit     Description
  X                  input                            0           X
  Y                  input                            0           Y
  Z                  input                            0           Z
  Heading            input                            0           Heading
  Pitch              input                            0           Pitch
  Roll               input                            0           Roll
  Speed              input                            0           Speed
  timestamps     

In [3]:
model_description = read_model_description(fmu)

# 提取输入变量
inputs = []
for variable in model_description.modelVariables:
    if variable.causality == 'input':  # 输入变量
        inputs.append(variable.name)

# 提取输出变量
outputs = []
for variable in model_description.modelVariables:
    if variable.causality == 'output':  # 输出变量
        outputs.append(variable.name)

print("输入变量:", inputs)
print("输出变量:", outputs)

输入变量: ['X', 'Y', 'Z', 'Heading', 'Pitch', 'Roll', 'Speed']
输出变量: ['timestamps', 'X_1', 'Y_1', 'Z_1', 'Heading_1', 'Pitch_1', 'Roll_1', 'Speed_1']


In [4]:
np.random.seed(42)
start_time = 0
stop_time = 5
step_size = 0.1

timestamps = np.arange(start_time, stop_time, step_size)

# X = list(np.random.uniform(-10, 10, size=len(timestamps)))
# Y = list(np.random.uniform(-10, 10, size=len(timestamps)))
# Z = list(np.random.uniform(-10, 10, size=len(timestamps)))
# heading = list(np.random.uniform(-90, 90, size=len(timestamps)))
# pitch = list(np.random.uniform(-90, 90, size=len(timestamps)))
# roll = list(np.random.uniform(-90, 90, size=len(timestamps)))
# speed = list(np.random.uniform(0, 100, size=len(timestamps)))

X = list(np.random.randint(-10, 11, size=len(timestamps)))
Y = list(np.random.randint(-10, 11, size=len(timestamps)))
Z = list(np.random.randint(-10, 11, size=len(timestamps)))
heading = list(np.random.randint(-90, 91, size=len(timestamps)))
pitch = list(np.random.randint(-90, 91, size=len(timestamps)))
roll = list(np.random.randint(-90, 91, size=len(timestamps)))
speed = list(np.random.randint(50, 101, size=len(timestamps)))

input_data_list = np.array(list(zip(timestamps, X, Y, Z, heading, pitch, roll, speed)),
                           dtype=[('time', np.float64),  # 添加时间列
                                  ('X', np.float64), ('Y', np.float64), 
                                  ('Z', np.float64), ('Heading', np.float64),
                                  ('Pitch', np.float64), ('Roll', np.float64),
                                  ('Speed', np.float64)])


print(input_data_list)

[(0. , -2.50919762,  9.39169256, -9.37141629,  73.48785947,  25.56569631, -36.99919943,  5.16817212)
 (0.1,  9.01428613,  5.50265647,  2.72820823, -46.87885968, -74.8548063 , -20.68240885, 53.13546316)
 (0.2,  4.63987884,  8.78997883, -3.71288038, -63.91892302, -60.90683146,  63.20460087, 54.06351216)
 (0.3,  1.97316968,  7.89654701,  0.17141382,  -1.89850315,  71.73975393, -32.95403907, 63.74299015)
 (0.4, -6.87962719,  1.95799958,  8.15132948,  87.41708174,  19.15723074, -59.4913056 , 72.60913337)
 (0.5, -6.88010959,  8.4374847 , -5.01415542, -46.43005113, -88.34453071,  10.22422724, 97.58520795)
 (0.6, -8.83832776, -8.23014996, -1.79234154,  30.98439853, -71.73512228,  78.50785935, 51.63003483)
 (0.7,  7.32352292, -6.08034275,  5.11102277,  47.09153076,  29.43031844,  35.2853634 , 32.29564729)
 (0.8,  2.02230023, -9.09545422, -5.42403669, -47.22524208, -89.08891491,  12.61101062, 79.51861948)
 (0.9,  4.16145156, -3.49339338, -8.4604018 ,  41.07894275, -61.05455074, -72.50823112, 27.

In [5]:
result = simulate_fmu(fmu,
                           start_time=start_time, stop_time=stop_time, step_size=step_size,
                           input=input_data_list,  # 确保 input 是一个 numpy 数组
                           output=outputs)
print(result.dtype)
print(result)

[('time', '<f8'), ('timestamps', '<f8'), ('X_1', '<f8'), ('Y_1', '<f8'), ('Z_1', '<f8'), ('Heading_1', '<f8'), ('Pitch_1', '<f8'), ('Roll_1', '<f8'), ('Speed_1', '<f8')]
[(0. , 0. , -1.50919762, 10.39169256, -8.37141629,  74.48785947,  26.56569631, -35.99919943,  6.16817212)
 (0.1, 0.1, -1.50919762, 10.39169256, -8.37141629,  74.48785947,  26.56569631, -35.99919943,  6.16817212)
 (0.2, 0.2, 10.01428613,  6.50265647,  3.72820823, -45.87885968, -73.8548063 , -19.68240885, 54.13546316)
 (0.3, 0.3,  5.63987884,  9.78997883, -2.71288038, -62.91892302, -59.90683146,  64.20460087, 55.06351216)
 (0.4, 0.4,  2.97316968,  8.89654701,  1.17141382,  -0.89850315,  72.73975393, -31.95403907, 64.74299015)
 (0.5, 0.5, -5.87962719,  2.95799958,  9.15132948,  88.41708174,  20.15723074, -58.4913056 , 73.60913337)
 (0.6, 0.6, -5.88010959,  9.4374847 , -4.01415542, -45.43005113, -87.34453071,  11.22422724, 98.58520795)
 (0.7, 0.7, -7.83832776, -7.23014996, -0.79234154,  31.98439853, -70.73512228,  79.50785

In [6]:
result_timestamp = result[result.dtype.names[1]]  # Assuming 'timestamp' is the correct field name
result_location = np.column_stack((result[result.dtype.names[2]], result[result.dtype.names[3]], result[result.dtype.names[4]]))  # Combine X and Y for location
result_angle = np.column_stack((result[result.dtype.names[5]], result[result.dtype.names[6]], result[result.dtype.names[7]]))  # Combine heading and pitch for angle
result_speed = result[result.dtype.names[-1]]  # Access speed directly

# print(result_location)

In [7]:
print(result_location)
print(result_angle)
print(result_speed)

[[-1.50919762 10.39169256 -8.37141629]
 [-1.50919762 10.39169256 -8.37141629]
 [10.01428613  6.50265647  3.72820823]
 [ 5.63987884  9.78997883 -2.71288038]
 [ 2.97316968  8.89654701  1.17141382]
 [-5.87962719  2.95799958  9.15132948]
 [-5.88010959  9.4374847  -4.01415542]
 [-7.83832776 -7.23014996 -0.79234154]
 [ 8.32352292 -5.08034275  6.11102277]
 [ 3.02230023 -8.09545422 -4.42403669]
 [ 5.16145156 -2.49339338 -7.4604018 ]
 [-8.58831011 -1.22645421 -3.20497094]
 [10.39819704 -3.57301936 -5.77557425]
 [ 7.64885282  7.57475018  9.59395305]
 [-4.75321779 -1.86493347  7.16240759]
 [-5.36350066 -3.38130981  3.66807513]
 [-5.3319098   1.85392166  8.4292118 ]
 [-2.91515514 -6.1815155   7.07344154]
 [ 1.49512863  7.04393962 -5.26859882]
 [-0.36109963 -7.50898713  8.85117997]
 [-3.1754172  10.73773873  1.78684484]
 [ 3.23705789  6.44489539  7.1488031 ]
 [-6.21012279 -5.02568637  8.921826  ]
 [-3.15710703 -8.88955766 -2.6399305 ]
 [-1.67276313  7.30922857 -6.79896151]
 [ 0.12139968  5.13714688